# Generated by Django 3.0.6 on 2023-07-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_adminlog_recommend_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recommend_movie',
        ),
        migrations.DeleteModel(
            name='AdminLog',
        ),
    ]
