# Generated by Django 3.0.6 on 2023-07-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20230706_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
