# Generated by Django 3.0.6 on 2023-07-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.IntegerField(default='2000', max_length=15),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='no description is available', max_length=5000),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='douban_rate',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
